name: Build and Package

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Clone private repository
      env:
        PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        PRIVATE_REPO_URL: ${{ secrets.PRIVATE_REPO_URL }}
      run: |
        # 克隆私有仓库
        git clone https://${PRIVATE_REPO_TOKEN}@${PRIVATE_REPO_URL} private-repo
        
        # 移动私有仓库内容到指定目录
        mkdir -p src/private-content
        cp -r private-repo/* src/private-content/
        
        # 清理克隆的仓库目录
        rm -rf private-repo
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Package application
      run: |
        # 创建打包目录
        mkdir -p dist/package
        
        # 复制构建产物
        cp -r build/* dist/package/
        
        # 创建压缩包
        cd dist
        tar -czf application-package-$(date +%Y%m%d-%H%M%S).tar.gz package/
        
        # 创建zip文件
        zip -r application-package-$(date +%Y%m%d-%H%M%S).zip package/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/*.tar.gz
          dist/*.zip
        retention-days: 30
    
    - name: Upload to release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.tar.gz
          dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}